export const CHANGE_COLOR = 'BACKGROUNDCOLOR_CHANGE_COLOR';
export const RESET_COLOR = 'BACKGROUNDCOLOR_RESET_COLOR';

export const STORE_USER_TOKEN = 'STORE_USER_TOKEN';
export const PURGE_USER_TOKEN = 'PURGE_USER_TOKEN';
export const STORE_FCM_TOKEN = 'STORE_FCM_TOKEN';
export const PURGE_FCM_TOKEN = 'PURGE_FCM_TOKEN';

export const SAVE_USER_OBJECT = 'SAVE_USER_OBJECT';
export const PURGE_USER_OBJECT = 'PURGE_USER_OBJECT';
export const SAVE_USER_FILTER = 'SAVE_USER_FILTER';
export const PURGE_USER_FILTER = 'PURGE_USER_FILTER';
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';
export const PURGE_USER_DETAILS = 'PURGE_USER_DETAILS';
export const SAVE_USER_CREATED_EVENTS = 'SAVE_USER_CREATED_EVENTS';
export const PURGE_USER_CREATED_EVENTS = 'PURGE_USER_CREATED_EVENTS';
export const SAVE_USER_FOLLOWING_TOPICS = 'SAVE_USER_FOLLOWING_TOPICS';
export const PURGE_USER_FOLLOWING_TOPICS = 'PURGE_USER_FOLLOWING_TOPICS';
export const SAVE_USER_GOING_TO = 'SAVE_USER_GOING_TO';
export const PURGE_USER_GOING_TO = 'PURGE_USER_GOING_TO';
export const SAVE_USER_INVITED_TO = 'SAVE_USER_INVITED_TO';
export const PURGE_USER_INVITED_TO = 'PURGE_USER_INVITED_TO';
export const SAVE_USER_INTERESTED_IN = 'SAVE_USER_INTERESTED_IN';
export const PURGE_USER_INTERESTED_IN = 'PURGE_USER_INTERESTED_IN';
export const SAVE_USER_PENDING_INCOMING_RELATIONSHIPS = 'SAVE_USER_PENDING_INCOMING_RELATIONSHIPS';
export const PURGE_USER_PENDING_INCOMING_RELATIONSHIPS = 'PURGE_USER_PENDING_INCOMING_RELATIONSHIPS';
export const SAVE_USER_PENDING_OUTGOING_RELATIONSHIPS = 'SAVE_USER_PENDING_OUTGOING_RELATIONSHIPS';
export const PURGE_USER_PENDING_OUTGOING_RELATIONSHIPS = 'PURGE_USER_PENDING_OUTGOING_RELATIONSHIPS';
export const SAVE_USER_CONTACTS = 'SAVE_USER_CONTACTS';
export const PURGE_USER_CONTACTS = 'PURGE_USER_CONTACTS';
export const SAVE_USER_BLOCKED_USERS = 'SAVE_USER_BLOCKED_USERS';
export const PURGE_USER_BLOCKED_USERS = 'PURGE_USER_BLOCKED_USERS'; 

export const SAVE_CURRENT_EVENT = 'SAVE_CURRENT_EVENT';
export const PURGE_CURRENT_EVENT = 'PURGE_CURRENT_EVENT';
export const SAVE_CURRENT_EVENT_MESSAGES = 'SAVE_CURRENT_EVENT_MESSAGES';
export const PURGE_CURRENT_EVENT_MESSAGES = 'PURGE_CURRENT_EVENT_MESSAGES';

export const SAVE_ACHIEVEMENTS = 'SAVE_ACHIEVEMENTS';
export const PURGE_ACHIEVEMENTS = 'PURGE_ACHIEVEMENTS';

export const SAVE_DISTANCE_MEASURE = 'SAVE_DISTANCE_MEASURE';
export const SAVE_NOTIFICATION_SETTINGS = 'SAVE_NOTIFICATION_SETTINGS';
export const PURGE_NOTIFICATION_SETTINGS = 'PURGE_NOTIFICATION_SETTINGS';

export const ADD_USER_LOCATION = 'ADD_USER_LOCATION';
export const REMOVE_USER_LOCATION = 'REMOVE_USER_LOCATION';
export const PURGE_USER_LOCATION = 'PURGE_USER_LOCATION';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const RESET_SELECTED_LOCATION = 'RESET_SELECTED_LOCATION';