export const CHANGE_COLOR = 'BACKGROUNDCOLOR_CHANGE_COLOR';
export const RESET_COLOR = 'BACKGROUNDCOLOR_RESET_COLOR';

export const STORE_USER_TOKEN = 'STORE_USER_TOKEN';
export const PURGE_USER_TOKEN = 'PURGE_USER_TOKEN';
export const STORE_FCM_TOKEN = 'STORE_FCM_TOKEN';
export const PURGE_FCM_TOKEN = 'PURGE_FCM_TOKEN';

export const SAVE_USER_OBJECT = 'SAVE_USER_OBJECT';
export const PURGE_USER_OBJECT = 'PURGE_USER_OBJECT';
export const SAVE_USER_FILTER = 'SAVE_USER_FILTER';
export const PURGE_USER_FILTER = 'PURGE_USER_FILTER';

export const SAVE_CURRENT_EVENT = 'SAVE_CURRENT_EVENT';
export const PURGE_CURRENT_EVENT = 'PURGE_CURRENT_EVENT';
export const SAVE_CURRENT_EVENT_MESSAGES = 'SAVE_CURRENT_EVENT_MESSAGES';
export const PURGE_CURRENT_EVENT_MESSAGES = 'PURGE_CURRENT_EVENT_MESSAGES';

export const SAVE_ACHIEVEMENTS = 'SAVE_ACHIEVEMENTS';
export const PURGE_ACHIEVEMENTS = 'PURGE_ACHIEVEMENTS';

export const SAVE_DISTANCE_MEASURE = 'SAVE_DISTANCE_MEASURE';
export const SAVE_NOTIFICATION_SETTINGS = 'SAVE_NOTIFICATION_SETTINGS';
export const PURGE_NOTIFICATION_SETTINGS = 'PURGE_NOTIFICATION_SETTINGS';

export const ADD_USER_LOCATION = 'ADD_USER_LOCATION';
export const REMOVE_USER_LOCATION = 'REMOVE_USER_LOCATION';
export const PURGE_USER_LOCATION = 'PURGE_USER_LOCATION';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const RESET_SELECTED_LOCATION = 'RESET_SELECTED_LOCATION';